<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ClassFinance</RootNamespace>
    <AssemblyName>ClassFinance</AssemblyName>
    <ApplicationIcon />
  </PropertyGroup>

</Project>
